version: '3.7'
services:
  opensearch:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch2.4.1
    environment:
      discovery.type: single-node
      plugins.security.disable: true
    ports:
      - 9200:9200
      - 9600:9600
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"